# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.2.1
group=org.sinytra
java_version=21

# Common
publish_name=wiki-exporter
minecraft_version=1.21.11
mod_name=Wiki Data Exporter
mod_author=Su5eD, Sinytra
mod_id=wiki_exporter
license=MIT
credits=
description=Automated game asset and data exporter
minecraft_version_range=[1.21.11, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
fabric_version=0.139.5+1.21.11
fabric_loader_version=0.18.2

# NeoForge
neoforge_version=21.11.6-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
