# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.3.0
group=org.sinytra
java_version=25

# Common
publish_name=wiki-exporter
minecraft_version=26.2
mod_name=Wiki Data Exporter
mod_author=Su5eD, Sinytra
mod_id=wiki_exporter
license=MIT
credits=
description=Automated game asset and data exporter
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric
fabric_version=0.157.0+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.59

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
