plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

sourceSets {
    metadata
    render
}

sourceSets.metadata {
    compileClasspath += sourceSets.main.compileClasspath
    runtimeClasspath += sourceSets.main.runtimeClasspath
}
sourceSets.render {
    compileClasspath += sourceSets.main.compileClasspath
    runtimeClasspath += sourceSets.main.runtimeClasspath
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    addModdingDependenciesTo sourceSets.metadata
    addModdingDependenciesTo sourceSets.render

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.metadata
            sourceSet sourceSets.render
        }
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    metadataImplementation sourceSets.main.output
    renderImplementation sourceSets.main.output
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

jar {
    from sourceSets.metadata.output
    from sourceSets.render.output
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile,
            sourceSets.metadata.java.sourceDirectories.singleFile,
            sourceSets.render.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile,
            sourceSets.metadata.resources.sourceDirectories.singleFile,
            sourceSets.render.resources.sourceDirectories.singleFile
}

